spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moses?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10485760 #单个文件10M
      max-request-size: 104857600 #单次文件100M
file:
  #上传的文件对外暴露的访问路径
  access-path-pattern: /u/**
  #文件上传目录
  upload-folder: C:\\moses\\
  #文件预览、下载的绝对路径
  access-prefix-url: http://localhost:8080/u
